
PRIKEY = ""
PUBKEY = ""
MY_TERMINAL_ID = "3ISO0140"
MY_SERIAL_ID = "python.app"
ACCOUNT_PWD = "112233"

# header strings
TIMESTAMP = "Timestamp"
TERMINAL_ID = "TerminalId"
NONCE = "Nonce"
SIGNATURE = "Signature"
AUTHORIZATION = "Authorization"
AUTHORIZATION_REALM = "InterswitchAuth"
ISO_8859_1 = "ISO-8859-1"
AUTH_TOKEN = "AuthToken"
APP_VERSION = "v1"

SANDBOX_ROUTE = "https://dev.interswitch.io/api/"
ROOT_LINK = SANDBOX_ROUTE

CLIENT_ID = "IKIAE49C7B4ACC0077BD80058314D71A66A7C6FCC286"
CLIENT_SECRET = "UtqTs3rO9XUzwKkeoCYKP0CCT9CDGmPePnonViczpWA="

POST_REQUEST = "POST"
GET_REQUEST = "GET"

AES_CBC_PKCS7_PADDING = "AES/CBC/PKCS7Padding"
RSA_NONE_OAEPWithSHA256AndMGF1Padding = "RSA/NONE/OAEPWithSHA256AndMGF1Padding"
