
PRIKEY = ""
PUBKEY = ""
MY_TERMINAL_ID = "3ISO0308"
MY_SERIAL_ID = "python.app"
ACCOUNT_PWD = "112233"

# header strings
TIMESTAMP = "Timestamp"
TERMINAL_ID = "3ISO0308"
NONCE = "Nonce"
SIGNATURE = "Signature"
AUTHORIZATION = "Authorization"
AUTHORIZATION_REALM = "InterswitchAuth"
ISO_8859_1 = "ISO-8859-1"
AUTH_TOKEN = "AuthToken"
APP_VERSION = "v1"

SANDBOX_ROUTE = "https://dev.interswitch.io/api/v1/phoenix/"
ROOT_LINK = SANDBOX_ROUTE

CLIENT_ID = "IKIAF3229850AB4F01D6A710F4F7131A6B68B5BDFC43"
CLIENT_SECRET = "qz7XclZk3V8yLLZsIXBqqa2zJLrxCDEGq8TCp1JsFx8="

POST_REQUEST = "POST"
GET_REQUEST = "GET"

AES_CBC_PKCS7_PADDING = "AES/CBC/PKCS7Padding"
RSA_NONE_OAEPWithSHA256AndMGF1Padding = "RSA/NONE/OAEPWithSHA256AndMGF1Padding"
